12:49:33.893 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection or unknown field.Parameter index out of range (1 > number of parameters, which is 0).
13:54:51.363 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - Start findAll().
13:54:51.389 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - Has found next user = User{role=ADMINISTRATOR, id='1', userName='admin', password='admin', email='admin@mail.ru', firstName='admin', lastName='admin', isActive=true, dateJoined=2021-08-09, photo=null}
13:54:51.389 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - Has found next user = User{role=MASTER, id='2', userName='master1', password='master1', email='master1@mail.ru', firstName='master1', lastName='master1', isActive=true, dateJoined=2021-08-09, photo=null}
13:54:51.390 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - Has found next user = User{role=CLIENT, id='3', userName='client1', password='client1', email='client1@mail.ru', firstName='client1', lastName='client1', isActive=true, dateJoined=2021-08-09, photo=null}
13:54:51.390 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - Has found next user = User{role=CLIENT, id='4', userName='client2', password='client2', email='client2@mail.ru', firstName='client2', lastName='client2', isActive=true, dateJoined=2021-08-09, photo=null}
13:54:51.390 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - Has found next users : [User{role=ADMINISTRATOR, id='1', userName='admin', password='admin', email='admin@mail.ru', firstName='admin', lastName='admin', isActive=true, dateJoined=2021-08-09, photo=null}, User{role=MASTER, id='2', userName='master1', password='master1', email='master1@mail.ru', firstName='master1', lastName='master1', isActive=true, dateJoined=2021-08-09, photo=null}, User{role=CLIENT, id='3', userName='client1', password='client1', email='client1@mail.ru', firstName='client1', lastName='client1', isActive=true, dateJoined=2021-08-09, photo=null}, User{role=CLIENT, id='4', userName='client2', password='client2', email='client2@mail.ru', firstName='client2', lastName='client2', isActive=true, dateJoined=2021-08-09, photo=null}]
15:05:00.678 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection.Can not issue data manipulation statements with executeQuery().
15:05:45.731 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection.Can not issue data manipulation statements with executeQuery().
15:07:30.194 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection.Can not issue data manipulation statements with executeQuery().
15:08:08.536 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection.Can not issue data manipulation statements with executeQuery().
15:09:15.226 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection.Can not issue data manipulation statements with executeQuery().
15:36:08.658 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection or unknown field.
15:37:06.395 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection or unknown field.
15:37:53.790 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection or unknown field.
16:17:15.509 [main] INFO  by.epam.litvinko.beautysalon.dao.UserDao - User id = 16 don't exist.
16:18:26.706 [main] ERROR by.epam.litvinko.beautysalon.dao.UserDao - Prepare statement can't be take from connection or unknown field.You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', username = 'update1', password = 'client3', email = 'client3@mail.ru', first_n' at line 1
